apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    cekit.io/version: 3.7.0
    commit.image.appsody.dev/date: Wed Sep 2 21:51:55 2020 -0700
    commit.image.appsody.dev/message: improve tests and fix bug in serialization,
      improve deployment too
    commit.stack.appsody.dev/contextDir: /experimental/ibm-gse-eda-quarkus
    commit.stack.appsody.dev/date: Sun Jul 19 21:24:37 2020 -0700
    commit.stack.appsody.dev/message: update python stack
    graalvm-archive-filename: graalvm-ce-linux-amd64-20.1.0-java11.tar.gz
    graalvm-archive-url: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
    graalvm-version: java11-20.1.0
    image.opencontainers.org/created: "2020-09-03T08:51:30-07:00"
    image.opencontainers.org/documentation: https://github.com/ibm-cloud-architecture/vaccine-monitoring-agent
    image.opencontainers.org/revision: 56a53030d6f5caa242bef5d80696640639174268-modified
    image.opencontainers.org/source: https://github.com/ibm-cloud-architecture/vaccine-monitoring-agent/tree/master
    image.opencontainers.org/url: https://github.com/ibm-cloud-architecture/vaccine-monitoring-agent
    k8s.io/description: Quarkus.io builder image for building Quarkus applications.
    k8s.io/display-name: Centos + GraalVM + Maven Image
    maintainer: Quarkus Team <quarkus-dev@googlegroups.com>
    openshift.io/expose-services: 8080:http
    openshift.io/tags: builder,java,quarkus
    org/label-schema.build-date: "20200809"
    org/label-schema.license: GPLv2
    org/label-schema.name: CentOS Base Image
    org/label-schema.schema-version: "1.0"
    org/label-schema.vendor: CentOS
    stack.appsody.dev/authors: jerome boyer <>
    stack.appsody.dev/configured: docker.io/ibmcase/ibm-gse-eda-quarkus:1.7.1
    stack.appsody.dev/created: "2020-09-01T17:34:37-07:00"
    stack.appsody.dev/description: Quarkus 1.7.1 runtime for running Java applications,
      kafka 2.5, Event Streams 10
    stack.appsody.dev/digest: sha256:38550f4dc4df3ca2be1017b7e58f877096657e8a70e9a7c6778fee8077e62351
    stack.appsody.dev/documentation: https://github.com/ibm-cloud-architecture/appsody-stacks/tree/master/experimental/ibm-gse-eda-quarkus/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: eb37bd327c8368bd45fad5327485644e1c2cfaf5-modified
    stack.appsody.dev/source: https://github.com/ibm-cloud-architecture/appsody-stacks/tree/master/experimental/ibm-gse-eda-quarkus/image
    stack.appsody.dev/tag: docker.io/ibmcase/ibm-gse-eda-quarkus:1.7.1
    stack.appsody.dev/title: IBM_GSE_EDA_Quarkus
    stack.appsody.dev/url: https://github.com/ibm-cloud-architecture/appsody-stacks/tree/master/experimental/ibm-gse-eda-quarkus
    stack.appsody.dev/vendor: CentOS
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: reefer-monitoring-agent
    stack.appsody.dev/id: ibm-gse-eda-quarkus
    stack.appsody.dev/version: 1.7.1
  name: reefer-monitoring-agent
  namespace: vaccine-solution
spec:
  applicationImage: ibmcase/reefer-monitor-agent:0.0.6
  createKnativeService: false
  env:
  - name: KAFKA_BROKERS
    valueFrom:
      configMapKeyRef:
        key: brokers
        name: kafka-brokers
  - name: KAFKA_USER
    valueFrom:
      configMapKeyRef:
        key: user
        name: kafka-brokers
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        key: user.password
        name: minimal-prod-ibm-es-kafka-user
  - name: KAFKA_CERT_PATH
    value: /deployments/certs/ca.p12
  - name: KAFKA_CERT_PWD
    valueFrom:
      secretKeyRef:
        key: ca.password
        name: minimal-prod-cluster-ca-cert
  - name: USER_CERT_PATH
    value: /deployments/certs/user.p12
  - name: USER_CERT_PWD
    valueFrom:
      secretKeyRef:
        key: user.password
        name: minimal-prod-ibm-es-kafka-user
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: reefer-monitoring-agent
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    port: 8080
    type: NodePort
  stack: ibm-gse-eda-quarkus
  version: 1.0.0
  volumeMounts:
  - mountPath: /deployments/certs/ca.p12
    name: es-cert
    readOnly: true
    subPath: ca.p12
  - mountPath: /deployments/certs/user.p12
    name: user-cert
    readOnly: true
    subPath: user.p12
  volumes:
  - name: user-cert
    secret:
      secretName: minimal-prod-ibm-es-kafka-user
  - name: es-cert
    secret:
      secretName: minimal-prod-cluster-ca-cert
