version: '3.5'
services:
  vaccinemonotoringagent:
    image: bmainaliibm/vaccine-monitoring:5.0
    expose:
      - 8080
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_API_KEY: ${KAFKA_API_KEY}
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vaccinemonotoringagent
    ports:
      - "4000:4000"