apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/version: 1.0.3
    app.kubernetes.io/name: reefer-monitoring-agent
  name: reefer-monitoring-agent