apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine-reefer-telemetries
  namespace: eventstreams
spec:
  partitions: 3
  replicas: 3
  topicName: vaccine-reefer-telemetries
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824